package rough;
import java.util.Scanner;
import java.io.*;
public class Prog07 {
	
	    public static void main(String args[]){
	        Scanner io = new Scanner(System.in);
	        int t=io.nextInt();
	        
	       
	       for(int i=0;i<=t;i++){
	            int a = io.nextInt();
	            int b = io.nextInt();
	            int n = io.nextInt();
	             int s1=a;
	            for(int j=0;j<n;j++){
	            
	          s1=s1+(int)Math.pow(2,j)*b;
	          
	          System.out.print(s1+" ");
	            
	        }
	    }
	    

	  //  System.out.println();
	    
		}
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                


}
